### ISSUE TITLE
Unhandled exception. System.TypeInitializationException: The type initializer for 'HDF.PInvoke.H5T' threw an exception.

### ISSUE THREAD

**Issue by siddhsql** [HDFGroup/HDF.PInvoke.NETStandard#21]
Hello,

I am trying to use this library to read and write data from HDF5 files. I am able to read data from a HDF5 file but when I try to save a HDF5 file I get this error:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'HDF.PInvoke.H5T' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'HDF.PInvoke.H5DLLImporter' threw an exception.
 ---> System.IO.FileNotFoundException: libhdf5.dylib
   at HDF.PInvoke.H5MacDllImporter..ctor(String libName) in /home/appveyor/projects/hdf-pinvoke-1-10/src/HDF.PInvoke.1.10/H5DLLImporter.cs:line 213
   at HDF.PInvoke.H5DLLImporter..cctor() in /home/appveyor/projects/hdf-pinvoke-1-10/src/HDF.PInvoke.1.10/H5DLLImporter.cs:line 70
   --- End of inner exception stack trace ---
   at HDF.PInvoke.H5T..cctor() in /home/appveyor/projects/hdf-pinvoke-1-10/submodules/HDF.PInvoke/HDF5/H5Tglobals.cs:line 38
   --- End of inner exception stack trace ---
   at HDF.PInvoke.H5T.get_NATIVE_INT32() in /home/appveyor/projects/hdf-pinvoke-1-10/submodules/HDF.PInvoke/HDF5/H5Tglobals.cs:line 332
   at HNSW.Net.Demo.Hdf5Utils.GetDatatype(Type type) in /Users/siddjain/github/hnsw-sharp-demo/Hdf5Utils.cs:line 153
   at HNSW.Net.Demo.Hdf5Utils.WriteDataset[T](Int64 fileId, String dataset, T[] data, UInt64[] dimensions) in /Users/siddjain/github/hnsw-sharp-demo/Hdf5Utils.cs:line 193
   at HNSW.Net.Demo.Program.Main() in /Users/siddjain/github/hnsw-sharp-demo/Program.cs:line 87
```

Its strange because while reading from HDF5 file I don't get any `System.IO.FileNotFoundException: libhdf5.dylib` exception.

The full code for the Hdf5Utils.cs class in the stacktrace can be seen here: https://github.com/siddhsql/hnsw-sharp-demo/blob/main/Hdf5Utils.cs

In addition I set `DYLD_LIBRARY_PATH` equal to the location where the `libhdf5.dylib` can be found. I am running on Mac os.

```
$ ls -al /opt/homebrew/lib/libhdf5.dylib
lrwxr-xr-x@ 1 siddjain  admin  39 Jul 10 17:34 /opt/homebrew/lib/libhdf5.dylib -> ../Cellar/hdf5/1.14.1/lib/libhdf5.dylib
```

I am using below version of the library:

```
<PackageReference Include="HDF.PInvoke.1.10" Version="1.10.612" />
```

Below are actual screenshots if it helps:

<img width="1684" alt="Pasted Graphic 1" src="https://github.com/HDFGroup/HDF.PInvoke.1.10/assets/127623723/7ae1bc86-659a-4fde-a10d-a9fc393778cb">

<img width="1511" alt="Pasted Graphic 2" src="https://github.com/HDFGroup/HDF.PInvoke.1.10/assets/127623723/b61bf864-9b6d-46b8-8158-229081d4ae2f">

**Comment by Apollo3zehn** [comment]
The libhdf5.dylib is already part of the Hdf.PInvoke.1.10 package. I am not 100% sure what the problem is, but you should make sure that the dylib file of the Nuget package is loaded instead of an external one. 

In case you are unable to solve the problem you might want to try the package PureHDF which comes without native dependencies and is able to read and write HDF5 files. I am working on a beta release (ready in a few days), where I will introduce a breaking change. Right now you can only read into 1D buffers using this method: `T[] datset.Read<T>()`. And then you can reshape your array afterwards using a costly copy operation. With the new API the signature changes to `T dataset.Read<T>()`, so something like `float[,] dataset.Read<float[,]>()` and more complex scenarios will become possible without extra copies (here are examples using attributes as the dataset API is not yet ported: https://github.com/Apollo3zehn/PureHDF/blob/feature-unify-api/tests/PureHDF.Tests/Reading/AttributeTests.cs)

**Comment by siddhsql** [comment]
thanks. With HDF.PInvoke I am able to read a dataset like this:

long datasetId = H5D.open(fileId, dataset);

But with PureHDF it seems I have to get the group first:
https://apollo3zehn.github.io/PureHDF/articles/reading.html

and w.r.t. this example:

var data3D = dataset
    .Read<int>()
    .ToArray3D(new long[] { -1, 7, 2 });

how do I get the dimensionality of the data in the first place?


with HDF.PInvoke I can do:

            // Get the datatype and dataspace
            long datatypeId = H5D.get_type(datasetId);
            long dataspaceId = H5D.get_space(datasetId);

            // Get the number of dimensions in the dataspace
            int rank = H5S.get_simple_extent_ndims(dataspaceId);

            // Get the dimensions of the dataspace
            ulong[] dimensions = new ulong[rank];
            H5S.get_simple_extent_dims(dataspaceId, dimensions, null);

but what is the corresponding code for PureHDF? Thanks.

**Comment by Apollo3zehn** [comment]
You can also directly get the dataset using its full path, something like `root.Dataset("/path/to/dataset")` should work.
The dimensions of a dataset you can find under the `Space` property: `dataset.Space.Dimensions`. 

If you have any problems, don't hesitate to create an issue in the PureHDF repository. I just wanted to give you an alternative as I know how annoying the native library resolution process can be :-)

**Comment by siddhsql** [comment]
Thanks Apollo. I am able to read HDF5 file now but running into several
issues trying to write a HDF5 file. I am using:
<PackageReference Include="PureHDF" Version="1.0.0-alpha.25" />
and this reference doc:
https://apollo3zehn.github.io/PureHDF/articles/writing.html
Problem 1: The type or namespace name 'H5Group' could not be found
Problem 2: H5File has no method Write on it
can you show me how to implement following methods using PureHDF:

var w = new Hdf5Writer("/path/to/hdf5/file");
w.AddDataset(mydata, "name-of-dataset"); // myData is float[][]
w.Save();

**Comment by Apollo3zehn** [comment]
Sorry, my bad. The documentation is more up to date than the currently released package on Nuget. Please add the `RestoreAdditionalProjectSources` and `PackageReference` properties as shown below. It must be that specific version (1.0.0-alpha.25.249) until the first beta version is released (a few days).

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RestoreAdditionalProjectSources>
      https://www.myget.org/F/apollo3zehn-dev/api/v3/index.json
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PureHDF" Version="1.0.0-alpha.25.249" />
  </ItemGroup>

</Project>

```

**Comment by Apollo3zehn** [comment]
```cs
var w = new Hdf5Writer("/path/to/hdf5/file");
w.AddDataset(mydata, "name-of-dataset"); // myData is float[][]
w.Save();
```

translates to

```cs
var data = new float[][] {
    new[] {
        1.1f, 2.2f, 3.3f
    },
    new[] {
        4.4f, 5.5f, 6.6f
    }
};

var file = new H5File() {
    ["name-of-dataset"] = data
};

file.Write("/path/to/hdf5/file");
```

**Comment by siddhsql** [comment]
Ok, thanks. i'll wait for the beta release. if you could update the thread
when the release is available on nuget, that would be great.

**Comment by Apollo3zehn** [comment]
I will keep you posted :-)

**Comment by Apollo3zehn** [comment]
The package has been released now: https://www.nuget.org/packages/PureHDF/1.0.0-beta.1

**Comment by siddhsql** [comment]
thanks. will check it out.
